### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-paginator#16]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [ ] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [ ] Modify `composer.json` to drop support for PHP less than 7.3
- [ ] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [ ] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [ ] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

**Comment by acelaya** [comment]
I can help with this if there's no one else on it yet.

**Comment by froschdesign** [comment]
@acelaya 
Go for it. Thanks in advance! 👍

**Comment by acelaya** [comment]
This might not be the best package to start with :sweat_smile: 

![image](https://user-images.githubusercontent.com/2719332/100316800-831c6c80-2fbb-11eb-9afc-a0faba41dcd8.png)

I'll check some of its dependencies first.

**Comment by acelaya** [comment]
Regarding the dependency on laminas config, should it bump to support only v3, or should it continue supporting v2 as well?

**Comment by froschdesign** [comment]
@acelaya 
> …should it bump to support only v3, or should it continue supporting v2 as well?

Version 2 fo laminas-config does not support version 8 of PHP. Remove it!

**Comment by acelaya** [comment]
Hey!

Sorry, I haven't been too active on this, as I was waiting to see if some of the dependencies got updated.

However, since I see the only blockers are dev dependencies and I have seen other laminas/mezzio packages getting released with "official" PHP 8 support before some of their own dependencies, I wanted to know what's your take on doing the same with this one.

I have already verified that, if you install dependencies with `--ignore-platform-req=php`, then all checks pass under PHP 8.

Would you be open to add this flag during CI and release a version which adds an explicit requirement on PHP that covers v8?

**Comment by froschdesign** [comment]
@acelaya 
> Sorry, I haven't been too active on this, as I was waiting to see if some of the dependencies got updated.

No problem at all. We are grateful for any help, in any form! 👍 

> However, since I see the only blockers are dev dependencies…

laminas-cache and laminas-json are still missing PHP 8 support. (The [automatic-releases](https://github.com/laminas/automatic-releases) action is missing for laminas-json.)
At the moment I see no chance for laminas-db. ([some background](https://github.com/laminas/technical-steering-committee/issues/56))
But we can extract the laminas-db support and add a wider support for other systems.

> Would you be open to add this flag during CI and release a version which adds an explicit requirement on PHP that covers v8?

We can do this but at the same time we need to open new issue reports for all related problems.

**Comment by acelaya** [comment]
> We can do this but at the same time we need to open new issue reports for all related problems.

Ok. Sounds good to me, I guess.

Does this mean I shall proceed then?

**Comment by froschdesign** [comment]
@acelaya 
> Does this mean I shall proceed then?

Go for it! 👍

**Comment by acelaya** [comment]
Looks like this is finally harder than I anticipated.

There are 2 tests failing due to a missuse of the `vsprintf` funtion inside laminas-db:

![image](https://user-images.githubusercontent.com/2719332/106377416-21062c00-639d-11eb-8cde-29ff6fc96601.png)

I guess previous versions of PHP were not that strict and did the cast to array internally, while it now fails with PHP 8.

~The coding style checks are also failing with this error~ (*scratching this out. This is not really a problem, as the styles are checked in a single PHP version*)

I think I will wait until a decission has been made regarding the dependency on laminas-db, and then I'll continue with this.

**Comment by Ocramius** [comment]
PHPCS is not yet PHP8-compatible - nothing that can be done there other than running PHPCS on PHP 7.4 for the time being.

**Comment by acelaya** [comment]
Oh, you are right. That shouldn't be a problem actually. I'll scratch it.

**Comment by froschdesign** [comment]
@acelaya 
laminas-db [now supports PHP 8.0](https://github.com/laminas/laminas-db/releases/tag/2.12.0).

**Comment by acelaya** [comment]
Yep, I saw it on Twitter yesterday 🙂
I'll try to tackle this one again.

**Comment by weierophinney** [comment]
@acelaya I'm already on it.
